# docker-compose.yml
version: '3.8'

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.5
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:9092,OUTSIDE://localhost:9093
      - --pandaproxy-addr
      - PLAINTEXT://0.0.0.0:8082
      - --advertise-pandaproxy-addr
      - http://localhost:8082
    ports:
      - "9092:9092"
      - "9093:9093"
      - "8082:8082"  # HTTP Proxy (опционально)
    volumes:
      - redpanda_data:/var/lib/redpanda/data

volumes:
  redpanda_data: